<a href="https://colab.research.google.com/github/Rehajel15/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# **Lists**

In [2]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[1, 2, 3, 4, 5]

# Numpy **Arrays**

In [14]:
np1 = np.random.rand(3,4)
np1

array([[0.82624554, 0.52773765, 0.80210542, 0.94093634],
       [0.80677636, 0.3217783 , 0.04619983, 0.64558908],
       [0.10207593, 0.26274479, 0.19522087, 0.7426109 ]])

In [4]:
np1.dtype

dtype('float64')

# **Tensors**

In [19]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[-1.6665,  1.6113,  0.7307, -0.1327],
        [ 0.1890, -0.1917,  0.4165, -0.4487],
        [-0.5956, -0.2258, -1.4476, -0.5097]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8262, 0.5277, 0.8021, 0.9409],
        [0.8068, 0.3218, 0.0462, 0.6456],
        [0.1021, 0.2627, 0.1952, 0.7426]], dtype=torch.float64)