<a href="https://colab.research.google.com/github/Rehajel15/Pytorch-Tutorial/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Tensor Math Operations**

*   Add, Subtract, Multiply, Divide, Remainders, Exponents
*   Shorthand and uh, Longhand
*   Reassignment

In [3]:
import torch
import numpy as np

In [10]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [5]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [7]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [11]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [12]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [14]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [15]:
# Mul Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [16]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [17]:
# Div Longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [19]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [20]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [21]:
# Exponents / power
tensor_a ** tensor_b

tensor([    1,    64,  2187, 65536])

In [22]:
# Pow Longhand
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [23]:
# Another way to write Longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [24]:
# Reassignment / _
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [25]:
tensor_a

tensor([1, 2, 3, 4])

In [26]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [27]:
tensor_a

tensor([ 6,  8, 10, 12])